version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment: 
      POSTGRES_DB: artisans
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    volumes:
      - ./create_fixtures.sql:/docker-entrypoint-initdb.d/create_fixtures.sql
  
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge